apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: {{ .Values.evApi1.hpaName }}
  namespace: {{ .Values.namespace }}
spec:
  minReplicas: {{ .Values.evApi1.minReplicas }}
  maxReplicas: {{ .Values.evApi1.maxReplicas }}
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ .Values.evApi1.deploymentName }}
  targetCPUUtilizationPercentage: {{ .Values.evApi1.targetCPUUtilizationPercentage }}